#!/usr/bin/env bash
# Transfers a file to a remote server's home directory using SCP

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

sudo scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "${USERNAME}@${SERVER_IP}:~/"
