#!/usr/bin/env bash
# Installs Nginx and configures a 301 redirect for /redirect_me to a YouTube video

# Update system and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Add 301 redirect inside the default server block
sudo sed -i '/^\s*location \/ {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
